spring:
  redis:
    host: localhost
    port: 6379
    password:


  db:
    host: localhost       # 保留配置，暂时不使用
    pw:

server:
  port: 8080

logging:
  level:
    org.springframework: INFO

ratelimit:
  capacity: 5           # 桶容量
  refillTokens: 1      # 每次补充令牌数
  refillIntervalMillis: 1000  # 补充间隔（毫秒）
  windowMillis: 60000   # 窗口长度：1 分钟
  limit: 100           # 每个窗口允许 100 次请求
